### ISSUE TITLE
Xray-action 2.4.2 release generates warning for usage of deprecated "set-output" command

### ISSUE THREAD

**Issue by jpickell49** [mikepenz/xray-action#681]
Requesting to have deprecated "set-output" command changed to environment files GITHUB_STATE and GITHUB_OUTPUT in this action.

set-output command is set to be depreciated by May 31st 2023 (end of this month).

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I also checked latest version (2.4.5) and set-output is also being used with this version.

Please have this replaced else the action will likely fail.

**Comment by mikepenz** [comment]
Since release `2.4.4` the `core` dependency was updated to no longer show the deprecation: https://github.com/mikepenz/xray-action/issues/609#issuecomment-1310294844

(Using the action myself and not seeing the deprecation for the new versions either)

Do you have the log output with the warning from 2.4.5 so I may have a closer look?

**Comment by jpickell49** [comment]
I actually tried v2.4.5 and no longer see the deprecation warning messages. Apologies for not doing this first and initially misdiagnosing the issue in v2.4.5.

Thanks for the assistance. This issue can be closed (resolved).
